/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * This file is generated by scripts/generate-model-registry.ts
 * Run: npm run models:generate
 */

import modelSystemStore from "./ModelSystemStore";
import product_ProductModel from "@mdl/product/server/models/ProductModel/ProductModel";

let loadedCount = 0;
let errorCount = 0;

export function registerAllModels() {
  console.group("🚀 Registering models from registry...");

  // Register product.ProductModel
  if (product_ProductModel && typeof product_ProductModel.getModelId === 'function') {
    const modelId = product_ProductModel.getModelId();
    if (modelId && typeof modelId === 'string') {
      modelSystemStore.set(modelId, product_ProductModel);
      console.log(`  ✓ Loaded ${modelId}`);
      loadedCount++;
    } else {
      console.warn(`  ⚠️  Model product.ProductModel: getModelId() returned invalid value`);
      errorCount++;
    }
  } else {
    console.warn(`  ⚠️  Model product.ProductModel: No default export or missing getModelId()`);
    errorCount++;
  }
  
  console.log(
    `✅ Registered ${loadedCount} models${errorCount > 0 ? ` (${errorCount} errors)` : ""}`
  );
  console.log(
    `📦 Model store: ${modelSystemStore.size()} model(s)`,
    modelSystemStore.getAllKeys()
  );
  console.groupEnd();
  
  return { loadedCount, errorCount };
}
