/**
 * Custom Next.js Server
 * Loads all models at server startup before handling requests
 */

import { createServer } from "http";
import next from "next";
import { parse } from "url";

const dev = process.env.NODE_ENV !== "production";
const hostname = "localhost";
const port = parseInt(process.env.PORT || "3000", 10);

// Create Next.js app
const app = next({ dev, hostname, port });
const handle = app.getRequestHandler();

/**
 * Load all model instances from generated registry
 * Registry is generated by scripts/generate-model-registry.ts
 */
async function loadAllModels() {
  try {
    // Import and use the generated registry
    const { registerAllModels } = await import(
      "./module-base/server/models/ModelRegistry"
    );
    registerAllModels();
  } catch (error: any) {
    console.error("❌ Failed to load model registry:", error?.message || error);
    console.log(
      "💡 Run: npm run models:generate to generate the registry file"
    );
  }
}

// Start server
app.prepare().then(async () => {
  // Load models BEFORE starting HTTP server
  await loadAllModels();

  // Create HTTP server
  createServer(async (req, res) => {
    try {
      const parsedUrl = parse(req.url || "", true);
      await handle(req, res, parsedUrl);
    } catch (err) {
      console.error("Error occurred handling", req.url, err);
      res.statusCode = 500;
      res.end("internal server error");
    }
  }).listen(port, () => {
    console.log(`> Ready on http://${hostname}:${port}`);
  });
});
